"""empty message

Revision ID: 183b1a7808c2
Revises: 3909f20212f5
Create Date: 2020-06-14 15:00:23.714912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183b1a7808c2'
down_revision = '3909f20212f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_money'), 'user', ['money'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_money'), table_name='user')
    op.drop_column('user', 'money')
    # ### end Alembic commands ###
