"""adding followers

Revision ID: 248b263dfd58
Revises: e665e1ea15aa
Create Date: 2020-06-06 22:47:48.236776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248b263dfd58'
down_revision = 'e665e1ea15aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
