"""game code

Revision ID: 3909f20212f5
Revises: f0dff1f8cc51
Create Date: 2020-06-09 11:31:46.580364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3909f20212f5'
down_revision = 'f0dff1f8cc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('code', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_tournament_code'), 'tournament', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_code'), table_name='tournament')
    op.drop_column('tournament', 'code')
    # ### end Alembic commands ###
