"""empty message

Revision ID: 8159b98cbf47
Revises: 0b17a7dc7cbc
Create Date: 2020-06-20 13:41:30.280996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8159b98cbf47'
down_revision = '0b17a7dc7cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gladiator', sa.Column('bio', sa.String(length=250), nullable=True))
    op.add_column('gladiator', sa.Column('height', sa.String(length=32), nullable=True))
    op.add_column('gladiator', sa.Column('quote', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gladiator', 'quote')
    op.drop_column('gladiator', 'height')
    op.drop_column('gladiator', 'bio')
    # ### end Alembic commands ###
