"""empty message

Revision ID: 9323a7bf5e0d
Revises: bd05b3f71b2c
Create Date: 2020-06-26 09:55:48.179909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9323a7bf5e0d'
down_revision = 'bd05b3f71b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money_rank', sa.Integer(), nullable=True))
    op.drop_index('ix_user_money', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_money', 'user', ['money'], unique=False)
    op.drop_column('user', 'money_rank')
    # ### end Alembic commands ###
