"""empty message

Revision ID: ae20cd078371
Revises: 183b1a7808c2
Create Date: 2020-06-14 15:01:41.344739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae20cd078371'
down_revision = '183b1a7808c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_money', table_name='user')
    op.drop_column('user', 'money')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', sa.INTEGER(), nullable=True))
    op.create_index('ix_user_money', 'user', ['money'], unique=False)
    # ### end Alembic commands ###
