"""empty message

Revision ID: bd05b3f71b2c
Revises: 
Create Date: 2020-06-23 12:45:32.693868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd05b3f71b2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_money'), 'user', ['money'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('gladiator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('aggro', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('quote', sa.String(length=140), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gladiator_aggro'), 'gladiator', ['aggro'], unique=False)
    op.create_index(op.f('ix_gladiator_name'), 'gladiator', ['name'], unique=False)
    op.create_index(op.f('ix_gladiator_speed'), 'gladiator', ['speed'], unique=False)
    op.create_index(op.f('ix_gladiator_strength'), 'gladiator', ['strength'], unique=False)
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_code'), 'tournament', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_code'), table_name='tournament')
    op.drop_table('tournament')
    op.drop_index(op.f('ix_gladiator_strength'), table_name='gladiator')
    op.drop_index(op.f('ix_gladiator_speed'), table_name='gladiator')
    op.drop_index(op.f('ix_gladiator_name'), table_name='gladiator')
    op.drop_index(op.f('ix_gladiator_aggro'), table_name='gladiator')
    op.drop_table('gladiator')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_money'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
