"""empty message

Revision ID: c222b173a9db
Revises: c16d9cdac9a5
Create Date: 2020-07-06 12:11:44.832544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c222b173a9db'
down_revision = 'c16d9cdac9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'name')
    # ### end Alembic commands ###
